# Import packages

In [92]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.linear_model import LinearRegression
import statsmodels.api as sm
import seaborn as sns
from datetime import datetime

# Read the dataset

In [93]:
gov = pd.read_csv('https://raw.githubusercontent.com/wingochau/Dissertation/main/gov_parkingslot_table61_eng.csv')

In [94]:
gov.head(3)

   YR_MTH    LOCATION   OPEN_DATE  CAP  NO_VEHICLE   UTL_RATE
0  201301  Yau Ma Tei  1957-10-12  772       31487  31.347150
1  201301  Star Ferry  1957-12-02  370       25521  38.648649
2  201301   City Hall  1959-11-12  165        4401  15.151515

In [95]:
gov_p = gov.loc[(gov['YR_MTH'] >= 201301)]

In [96]:
gov_p_usage = gov_p.groupby(['YR_MTH','LOCATION']).agg({"UTL_RATE" : np.mean})
gov_p_usage.rename(columns ={'UTL_RATE': 'gov_UTL_RATE'}, inplace=True)
gov_p_usage.tail(15)

                           gov_UTL_RATE
YR_MTH LOCATION
202011 Star Ferry             44.827586
       Tin Hau                69.158879
       Tsuen Wan              82.385321
       Yau Ma Tei             74.545455
202012 Aberdeen               76.450512
       City Hall              26.470588
       Kennedy Town           80.512821
       Kwai Fong              73.069680
       Rumsey Street          37.604790
       Shau Kei Wan           80.779221
       Sheung Fung Street     77.528090
       Star Ferry             40.053050
       Tin Hau                68.925234
       Tsuen Wan              83.119266
       Yau Ma Tei             60.571429

In [97]:
gov_p_usage.to_csv('gov_parking_processed.csv')

In [98]:
gov_usage = gov_p.groupby(['YR_MTH']).agg({"UTL_RATE" : np.mean})
gov_usage.rename(columns ={'UTL_RATE': 'gov_UTL_RATE'}, inplace=True)
gov_usage.tail(15)

        gov_UTL_RATE
YR_MTH
201910     64.787262
201911     62.892210
201912     64.012347
202001     62.337527
202002     63.363636
202003     64.038990
202004     63.354053
202005     64.675843
202006     64.917993
202007     64.741669
202008     63.617320
202009     64.344672
202010     63.433259
202011     66.195546
202012     64.098607

In [99]:
gov_usage_in = gov_usage.reset_index()
gov_usage_in

    YR_MTH  gov_UTL_RATE
0   201301     45.490305
1   201302     47.963943
2   201303     48.735716
3   201304     49.095071
4   201305     50.142495
..     ...           ...
91  202008     63.617320
92  202009     64.344672
93  202010     63.433259
94  202011     66.195546
95  202012     64.098607

[96 rows x 2 columns]

In [100]:
#gov_usage.to_csv('gov_parking_processed_month.csv')

In [101]:
gov_p_usage_t = gov_p_usage.reset_index()

In [102]:
gov_p_usage_t_0113 = gov_p_usage_t.loc[(gov_p_usage_t['YR_MTH'] == 201301)]
gov_p_usage_t_0213 = gov_p_usage_t.loc[(gov_p_usage_t['YR_MTH'] == 201302)]
gov_p_usage_t_0313 = gov_p_usage_t.loc[(gov_p_usage_t['YR_MTH'] == 201303)]
gov_p_usage_t_0413 = gov_p_usage_t.loc[(gov_p_usage_t['YR_MTH'] == 201304)]
gov_p_usage_t_0513 = gov_p_usage_t.loc[(gov_p_usage_t['YR_MTH'] == 201305)]
gov_p_usage_t_0613 = gov_p_usage_t.loc[(gov_p_usage_t['YR_MTH'] == 201306)]
gov_p_usage_t_0713 = gov_p_usage_t.loc[(gov_p_usage_t['YR_MTH'] == 201307)]
gov_p_usage_t_0813 = gov_p_usage_t.loc[(gov_p_usage_t['YR_MTH'] == 201308)]
gov_p_usage_t_0913 = gov_p_usage_t.loc[(gov_p_usage_t['YR_MTH'] == 201309)]
gov_p_usage_t_1013 = gov_p_usage_t.loc[(gov_p_usage_t['YR_MTH'] == 201310)]
gov_p_usage_t_1113 = gov_p_usage_t.loc[(gov_p_usage_t['YR_MTH'] == 201311)]
gov_p_usage_t_1213 = gov_p_usage_t.loc[(gov_p_usage_t['YR_MTH'] == 201312)]

gov_p_usage_t_0114 = gov_p_usage_t.loc[(gov_p_usage_t['YR_MTH'] == 201401)]
gov_p_usage_t_0214 = gov_p_usage_t.loc[(gov_p_usage_t['YR_MTH'] == 201402)]
gov_p_usage_t_0314 = gov_p_usage_t.loc[(gov_p_usage_t['YR_MTH'] == 201403)]
gov_p_usage_t_0414 = gov_p_usage_t.loc[(gov_p_usage_t['YR_MTH'] == 201404)]
gov_p_usage_t_0514 = gov_p_usage_t.loc[(gov_p_usage_t['YR_MTH'] == 201405)]
gov_p_usage_t_0614 = gov_p_usage_t.loc[(gov_p_usage_t['YR_MTH'] == 201406)]
gov_p_usage_t_0714 = gov_p_usage_t.loc[(gov_p_usage_t['YR_MTH'] == 201407)]
gov_p_usage_t_0814 = gov_p_usage_t.loc[(gov_p_usage_t['YR_MTH'] == 201408)]
gov_p_usage_t_0914 = gov_p_usage_t.loc[(gov_p_usage_t['YR_MTH'] == 201409)]
gov_p_usage_t_1014 = gov_p_usage_t.loc[(gov_p_usage_t['YR_MTH'] == 201410)]
gov_p_usage_t_1114 = gov_p_usage_t.loc[(gov_p_usage_t['YR_MTH'] == 201411)]
gov_p_usage_t_1214 = gov_p_usage_t.loc[(gov_p_usage_t['YR_MTH'] == 201412)]

gov_p_usage_t_0115 = gov_p_usage_t.loc[(gov_p_usage_t['YR_MTH'] == 201501)]
gov_p_usage_t_0215 = gov_p_usage_t.loc[(gov_p_usage_t['YR_MTH'] == 201502)]
gov_p_usage_t_0315 = gov_p_usage_t.loc[(gov_p_usage_t['YR_MTH'] == 201503)]
gov_p_usage_t_0415 = gov_p_usage_t.loc[(gov_p_usage_t['YR_MTH'] == 201504)]
gov_p_usage_t_0515 = gov_p_usage_t.loc[(gov_p_usage_t['YR_MTH'] == 201505)]
gov_p_usage_t_0615 = gov_p_usage_t.loc[(gov_p_usage_t['YR_MTH'] == 201506)]
gov_p_usage_t_0715 = gov_p_usage_t.loc[(gov_p_usage_t['YR_MTH'] == 201507)]
gov_p_usage_t_0815 = gov_p_usage_t.loc[(gov_p_usage_t['YR_MTH'] == 201508)]
gov_p_usage_t_0915 = gov_p_usage_t.loc[(gov_p_usage_t['YR_MTH'] == 201509)]
gov_p_usage_t_1015 = gov_p_usage_t.loc[(gov_p_usage_t['YR_MTH'] == 201510)]
gov_p_usage_t_1115 = gov_p_usage_t.loc[(gov_p_usage_t['YR_MTH'] == 201511)]
gov_p_usage_t_1215 = gov_p_usage_t.loc[(gov_p_usage_t['YR_MTH'] == 201512)]

gov_p_usage_t_0116 = gov_p_usage_t.loc[(gov_p_usage_t['YR_MTH'] == 201601)]
gov_p_usage_t_0216 = gov_p_usage_t.loc[(gov_p_usage_t['YR_MTH'] == 201602)]
gov_p_usage_t_0316 = gov_p_usage_t.loc[(gov_p_usage_t['YR_MTH'] == 201603)]
gov_p_usage_t_0416 = gov_p_usage_t.loc[(gov_p_usage_t['YR_MTH'] == 201604)]
gov_p_usage_t_0516 = gov_p_usage_t.loc[(gov_p_usage_t['YR_MTH'] == 201605)]
gov_p_usage_t_0616 = gov_p_usage_t.loc[(gov_p_usage_t['YR_MTH'] == 201606)]
gov_p_usage_t_0716 = gov_p_usage_t.loc[(gov_p_usage_t['YR_MTH'] == 201607)]
gov_p_usage_t_0816 = gov_p_usage_t.loc[(gov_p_usage_t['YR_MTH'] == 201608)]
gov_p_usage_t_0916 = gov_p_usage_t.loc[(gov_p_usage_t['YR_MTH'] == 201609)]
gov_p_usage_t_1016 = gov_p_usage_t.loc[(gov_p_usage_t['YR_MTH'] == 201610)]
gov_p_usage_t_1116 = gov_p_usage_t.loc[(gov_p_usage_t['YR_MTH'] == 201611)]
gov_p_usage_t_1216 = gov_p_usage_t.loc[(gov_p_usage_t['YR_MTH'] == 201612)]

gov_p_usage_t_0117 = gov_p_usage_t.loc[(gov_p_usage_t['YR_MTH'] == 201701)]
gov_p_usage_t_0217 = gov_p_usage_t.loc[(gov_p_usage_t['YR_MTH'] == 201702)]
gov_p_usage_t_0317 = gov_p_usage_t.loc[(gov_p_usage_t['YR_MTH'] == 201703)]
gov_p_usage_t_0417 = gov_p_usage_t.loc[(gov_p_usage_t['YR_MTH'] == 201704)]
gov_p_usage_t_0517 = gov_p_usage_t.loc[(gov_p_usage_t['YR_MTH'] == 201705)]
gov_p_usage_t_0617 = gov_p_usage_t.loc[(gov_p_usage_t['YR_MTH'] == 201706)]
gov_p_usage_t_0717 = gov_p_usage_t.loc[(gov_p_usage_t['YR_MTH'] == 201707)]
gov_p_usage_t_0817 = gov_p_usage_t.loc[(gov_p_usage_t['YR_MTH'] == 201708)]
gov_p_usage_t_0917 = gov_p_usage_t.loc[(gov_p_usage_t['YR_MTH'] == 201709)]
gov_p_usage_t_1017 = gov_p_usage_t.loc[(gov_p_usage_t['YR_MTH'] == 201710)]
gov_p_usage_t_1117 = gov_p_usage_t.loc[(gov_p_usage_t['YR_MTH'] == 201711)]
gov_p_usage_t_1217 = gov_p_usage_t.loc[(gov_p_usage_t['YR_MTH'] == 201712)]


gov_p_usage_t_0118 = gov_p_usage_t.loc[(gov_p_usage_t['YR_MTH'] == 201801)]
gov_p_usage_t_0218 = gov_p_usage_t.loc[(gov_p_usage_t['YR_MTH'] == 201802)]
gov_p_usage_t_0318 = gov_p_usage_t.loc[(gov_p_usage_t['YR_MTH'] == 201803)]
gov_p_usage_t_0418 = gov_p_usage_t.loc[(gov_p_usage_t['YR_MTH'] == 201804)]
gov_p_usage_t_0518 = gov_p_usage_t.loc[(gov_p_usage_t['YR_MTH'] == 201805)]
gov_p_usage_t_0618 = gov_p_usage_t.loc[(gov_p_usage_t['YR_MTH'] == 201806)]
gov_p_usage_t_0718 = gov_p_usage_t.loc[(gov_p_usage_t['YR_MTH'] == 201807)]
gov_p_usage_t_0818 = gov_p_usage_t.loc[(gov_p_usage_t['YR_MTH'] == 201808)]
gov_p_usage_t_0918 = gov_p_usage_t.loc[(gov_p_usage_t['YR_MTH'] == 201809)]
gov_p_usage_t_1018 = gov_p_usage_t.loc[(gov_p_usage_t['YR_MTH'] == 201810)]
gov_p_usage_t_1118 = gov_p_usage_t.loc[(gov_p_usage_t['YR_MTH'] == 201811)]
gov_p_usage_t_1218 = gov_p_usage_t.loc[(gov_p_usage_t['YR_MTH'] == 201812)]

gov_p_usage_t_0119 = gov_p_usage_t.loc[(gov_p_usage_t['YR_MTH'] == 201901)]
gov_p_usage_t_0219 = gov_p_usage_t.loc[(gov_p_usage_t['YR_MTH'] == 201902)]
gov_p_usage_t_0319 = gov_p_usage_t.loc[(gov_p_usage_t['YR_MTH'] == 201903)]
gov_p_usage_t_0419 = gov_p_usage_t.loc[(gov_p_usage_t['YR_MTH'] == 201904)]
gov_p_usage_t_0519 = gov_p_usage_t.loc[(gov_p_usage_t['YR_MTH'] == 201905)]
gov_p_usage_t_0619 = gov_p_usage_t.loc[(gov_p_usage_t['YR_MTH'] == 201906)]
gov_p_usage_t_0719 = gov_p_usage_t.loc[(gov_p_usage_t['YR_MTH'] == 201907)]
gov_p_usage_t_0819 = gov_p_usage_t.loc[(gov_p_usage_t['YR_MTH'] == 201908)]
gov_p_usage_t_0919 = gov_p_usage_t.loc[(gov_p_usage_t['YR_MTH'] == 201909)]
gov_p_usage_t_1019 = gov_p_usage_t.loc[(gov_p_usage_t['YR_MTH'] == 201910)]
gov_p_usage_t_1119 = gov_p_usage_t.loc[(gov_p_usage_t['YR_MTH'] == 201911)]
gov_p_usage_t_1219 = gov_p_usage_t.loc[(gov_p_usage_t['YR_MTH'] == 201912)]


gov_p_usage_t_0120 = gov_p_usage_t.loc[(gov_p_usage_t['YR_MTH'] == 202001)]
gov_p_usage_t_0220 = gov_p_usage_t.loc[(gov_p_usage_t['YR_MTH'] == 202002)]
gov_p_usage_t_0320 = gov_p_usage_t.loc[(gov_p_usage_t['YR_MTH'] == 202003)]
gov_p_usage_t_0420 = gov_p_usage_t.loc[(gov_p_usage_t['YR_MTH'] == 202004)]
gov_p_usage_t_0520 = gov_p_usage_t.loc[(gov_p_usage_t['YR_MTH'] == 202005)]
gov_p_usage_t_0620 = gov_p_usage_t.loc[(gov_p_usage_t['YR_MTH'] == 202006)]
gov_p_usage_t_0720 = gov_p_usage_t.loc[(gov_p_usage_t['YR_MTH'] == 202007)]
gov_p_usage_t_0820 = gov_p_usage_t.loc[(gov_p_usage_t['YR_MTH'] == 202008)]
gov_p_usage_t_0920 = gov_p_usage_t.loc[(gov_p_usage_t['YR_MTH'] == 202009)]
gov_p_usage_t_1020 = gov_p_usage_t.loc[(gov_p_usage_t['YR_MTH'] == 202010)]
gov_p_usage_t_1120 = gov_p_usage_t.loc[(gov_p_usage_t['YR_MTH'] == 202011)]
gov_p_usage_t_1220 = gov_p_usage_t.loc[(gov_p_usage_t['YR_MTH'] == 202012)]

In [103]:
gov_p_usage_t_0113_g = gov_p_usage_t_0113.groupby(['LOCATION']).agg({"gov_UTL_RATE" : np.mean})
gov_p_usage_t_0113_t = gov_p_usage_t_0113_g.T
gov_p_usage_t_0213_g = gov_p_usage_t_0213.groupby(['LOCATION']).agg({"gov_UTL_RATE" : np.mean})
gov_p_usage_t_0213_t = gov_p_usage_t_0213_g.T
gov_p_usage_t_0313_g = gov_p_usage_t_0313.groupby(['LOCATION']).agg({"gov_UTL_RATE" : np.mean})
gov_p_usage_t_0313_t = gov_p_usage_t_0313_g.T
gov_p_usage_t_0413_g = gov_p_usage_t_0413.groupby(['LOCATION']).agg({"gov_UTL_RATE" : np.mean})
gov_p_usage_t_0413_t = gov_p_usage_t_0413_g.T
gov_p_usage_t_0513_g = gov_p_usage_t_0513.groupby(['LOCATION']).agg({"gov_UTL_RATE" : np.mean})
gov_p_usage_t_0513_t = gov_p_usage_t_0513_g.T
gov_p_usage_t_0613_g = gov_p_usage_t_0613.groupby(['LOCATION']).agg({"gov_UTL_RATE" : np.mean})
gov_p_usage_t_0613_t = gov_p_usage_t_0613_g.T
gov_p_usage_t_0713_g = gov_p_usage_t_0713.groupby(['LOCATION']).agg({"gov_UTL_RATE" : np.mean})
gov_p_usage_t_0713_t = gov_p_usage_t_0713_g.T
gov_p_usage_t_0813_g = gov_p_usage_t_0813.groupby(['LOCATION']).agg({"gov_UTL_RATE" : np.mean})
gov_p_usage_t_0813_t = gov_p_usage_t_0813_g.T
gov_p_usage_t_0913_g = gov_p_usage_t_0913.groupby(['LOCATION']).agg({"gov_UTL_RATE" : np.mean})
gov_p_usage_t_0913_t = gov_p_usage_t_0913_g.T
gov_p_usage_t_1013_g = gov_p_usage_t_1013.groupby(['LOCATION']).agg({"gov_UTL_RATE" : np.mean})
gov_p_usage_t_1013_t = gov_p_usage_t_1013_g.T
gov_p_usage_t_1113_g = gov_p_usage_t_1113.groupby(['LOCATION']).agg({"gov_UTL_RATE" : np.mean})
gov_p_usage_t_1113_t = gov_p_usage_t_1113_g.T
gov_p_usage_t_1213_g = gov_p_usage_t_1213.groupby(['LOCATION']).agg({"gov_UTL_RATE" : np.mean})
gov_p_usage_t_1213_t = gov_p_usage_t_1213_g.T

gov_p_usage_t_0114_g = gov_p_usage_t_0114.groupby(['LOCATION']).agg({"gov_UTL_RATE" : np.mean})
gov_p_usage_t_0114_t = gov_p_usage_t_0114_g.T
gov_p_usage_t_0214_g = gov_p_usage_t_0214.groupby(['LOCATION']).agg({"gov_UTL_RATE" : np.mean})
gov_p_usage_t_0214_t = gov_p_usage_t_0214_g.T
gov_p_usage_t_0314_g = gov_p_usage_t_0314.groupby(['LOCATION']).agg({"gov_UTL_RATE" : np.mean})
gov_p_usage_t_0314_t = gov_p_usage_t_0314_g.T
gov_p_usage_t_0414_g = gov_p_usage_t_0414.groupby(['LOCATION']).agg({"gov_UTL_RATE" : np.mean})
gov_p_usage_t_0414_t = gov_p_usage_t_0414_g.T
gov_p_usage_t_0514_g = gov_p_usage_t_0514.groupby(['LOCATION']).agg({"gov_UTL_RATE" : np.mean})
gov_p_usage_t_0514_t = gov_p_usage_t_0514_g.T
gov_p_usage_t_0614_g = gov_p_usage_t_0614.groupby(['LOCATION']).agg({"gov_UTL_RATE" : np.mean})
gov_p_usage_t_0614_t = gov_p_usage_t_0614_g.T
gov_p_usage_t_0714_g = gov_p_usage_t_0714.groupby(['LOCATION']).agg({"gov_UTL_RATE" : np.mean})
gov_p_usage_t_0714_t = gov_p_usage_t_0714_g.T
gov_p_usage_t_0814_g = gov_p_usage_t_0814.groupby(['LOCATION']).agg({"gov_UTL_RATE" : np.mean})
gov_p_usage_t_0814_t = gov_p_usage_t_0814_g.T
gov_p_usage_t_0914_g = gov_p_usage_t_0914.groupby(['LOCATION']).agg({"gov_UTL_RATE" : np.mean})
gov_p_usage_t_0914_t = gov_p_usage_t_0914_g.T
gov_p_usage_t_1014_g = gov_p_usage_t_1014.groupby(['LOCATION']).agg({"gov_UTL_RATE" : np.mean})
gov_p_usage_t_1014_t = gov_p_usage_t_1014_g.T
gov_p_usage_t_1114_g = gov_p_usage_t_1114.groupby(['LOCATION']).agg({"gov_UTL_RATE" : np.mean})
gov_p_usage_t_1114_t = gov_p_usage_t_1114_g.T
gov_p_usage_t_1214_g = gov_p_usage_t_1214.groupby(['LOCATION']).agg({"gov_UTL_RATE" : np.mean})
gov_p_usage_t_1214_t = gov_p_usage_t_1214_g.T

gov_p_usage_t_0115_g = gov_p_usage_t_0115.groupby(['LOCATION']).agg({"gov_UTL_RATE" : np.mean})
gov_p_usage_t_0115_t = gov_p_usage_t_0115_g.T
gov_p_usage_t_0215_g = gov_p_usage_t_0215.groupby(['LOCATION']).agg({"gov_UTL_RATE" : np.mean})
gov_p_usage_t_0215_t = gov_p_usage_t_0215_g.T
gov_p_usage_t_0315_g = gov_p_usage_t_0315.groupby(['LOCATION']).agg({"gov_UTL_RATE" : np.mean})
gov_p_usage_t_0315_t = gov_p_usage_t_0315_g.T
gov_p_usage_t_0415_g = gov_p_usage_t_0415.groupby(['LOCATION']).agg({"gov_UTL_RATE" : np.mean})
gov_p_usage_t_0415_t = gov_p_usage_t_0415_g.T
gov_p_usage_t_0515_g = gov_p_usage_t_0515.groupby(['LOCATION']).agg({"gov_UTL_RATE" : np.mean})
gov_p_usage_t_0515_t = gov_p_usage_t_0515_g.T
gov_p_usage_t_0615_g = gov_p_usage_t_0615.groupby(['LOCATION']).agg({"gov_UTL_RATE" : np.mean})
gov_p_usage_t_0615_t = gov_p_usage_t_0615_g.T
gov_p_usage_t_0715_g = gov_p_usage_t_0715.groupby(['LOCATION']).agg({"gov_UTL_RATE" : np.mean})
gov_p_usage_t_0715_t = gov_p_usage_t_0715_g.T
gov_p_usage_t_0815_g = gov_p_usage_t_0815.groupby(['LOCATION']).agg({"gov_UTL_RATE" : np.mean})
gov_p_usage_t_0815_t = gov_p_usage_t_0815_g.T
gov_p_usage_t_0915_g = gov_p_usage_t_0915.groupby(['LOCATION']).agg({"gov_UTL_RATE" : np.mean})
gov_p_usage_t_0915_t = gov_p_usage_t_0915_g.T
gov_p_usage_t_1015_g = gov_p_usage_t_1015.groupby(['LOCATION']).agg({"gov_UTL_RATE" : np.mean})
gov_p_usage_t_1015_t = gov_p_usage_t_1015_g.T
gov_p_usage_t_1115_g = gov_p_usage_t_1115.groupby(['LOCATION']).agg({"gov_UTL_RATE" : np.mean})
gov_p_usage_t_1115_t = gov_p_usage_t_1115_g.T
gov_p_usage_t_1215_g = gov_p_usage_t_1215.groupby(['LOCATION']).agg({"gov_UTL_RATE" : np.mean})
gov_p_usage_t_1215_t = gov_p_usage_t_1215_g.T

gov_p_usage_t_0116_g = gov_p_usage_t_0116.groupby(['LOCATION']).agg({"gov_UTL_RATE" : np.mean})
gov_p_usage_t_0116_t = gov_p_usage_t_0116_g.T
gov_p_usage_t_0216_g = gov_p_usage_t_0216.groupby(['LOCATION']).agg({"gov_UTL_RATE" : np.mean})
gov_p_usage_t_0216_t = gov_p_usage_t_0216_g.T
gov_p_usage_t_0316_g = gov_p_usage_t_0316.groupby(['LOCATION']).agg({"gov_UTL_RATE" : np.mean})
gov_p_usage_t_0316_t = gov_p_usage_t_0316_g.T
gov_p_usage_t_0416_g = gov_p_usage_t_0416.groupby(['LOCATION']).agg({"gov_UTL_RATE" : np.mean})
gov_p_usage_t_0416_t = gov_p_usage_t_0416_g.T
gov_p_usage_t_0516_g = gov_p_usage_t_0516.groupby(['LOCATION']).agg({"gov_UTL_RATE" : np.mean})
gov_p_usage_t_0516_t = gov_p_usage_t_0516_g.T
gov_p_usage_t_0616_g = gov_p_usage_t_0616.groupby(['LOCATION']).agg({"gov_UTL_RATE" : np.mean})
gov_p_usage_t_0616_t = gov_p_usage_t_0616_g.T
gov_p_usage_t_0716_g = gov_p_usage_t_0716.groupby(['LOCATION']).agg({"gov_UTL_RATE" : np.mean})
gov_p_usage_t_0716_t = gov_p_usage_t_0716_g.T
gov_p_usage_t_0816_g = gov_p_usage_t_0816.groupby(['LOCATION']).agg({"gov_UTL_RATE" : np.mean})
gov_p_usage_t_0816_t = gov_p_usage_t_0816_g.T
gov_p_usage_t_0916_g = gov_p_usage_t_0916.groupby(['LOCATION']).agg({"gov_UTL_RATE" : np.mean})
gov_p_usage_t_0916_t = gov_p_usage_t_0916_g.T
gov_p_usage_t_1016_g = gov_p_usage_t_1016.groupby(['LOCATION']).agg({"gov_UTL_RATE" : np.mean})
gov_p_usage_t_1016_t = gov_p_usage_t_1016_g.T
gov_p_usage_t_1116_g = gov_p_usage_t_1116.groupby(['LOCATION']).agg({"gov_UTL_RATE" : np.mean})
gov_p_usage_t_1116_t = gov_p_usage_t_1116_g.T
gov_p_usage_t_1216_g = gov_p_usage_t_1216.groupby(['LOCATION']).agg({"gov_UTL_RATE" : np.mean})
gov_p_usage_t_1216_t = gov_p_usage_t_1216_g.T

gov_p_usage_t_0117_g = gov_p_usage_t_0117.groupby(['LOCATION']).agg({"gov_UTL_RATE" : np.mean})
gov_p_usage_t_0117_t = gov_p_usage_t_0117_g.T
gov_p_usage_t_0217_g = gov_p_usage_t_0217.groupby(['LOCATION']).agg({"gov_UTL_RATE" : np.mean})
gov_p_usage_t_0217_t = gov_p_usage_t_0217_g.T
gov_p_usage_t_0317_g = gov_p_usage_t_0317.groupby(['LOCATION']).agg({"gov_UTL_RATE" : np.mean})
gov_p_usage_t_0317_t = gov_p_usage_t_0317_g.T
gov_p_usage_t_0417_g = gov_p_usage_t_0417.groupby(['LOCATION']).agg({"gov_UTL_RATE" : np.mean})
gov_p_usage_t_0417_t = gov_p_usage_t_0417_g.T
gov_p_usage_t_0517_g = gov_p_usage_t_0517.groupby(['LOCATION']).agg({"gov_UTL_RATE" : np.mean})
gov_p_usage_t_0517_t = gov_p_usage_t_0517_g.T
gov_p_usage_t_0617_g = gov_p_usage_t_0617.groupby(['LOCATION']).agg({"gov_UTL_RATE" : np.mean})
gov_p_usage_t_0617_t = gov_p_usage_t_0617_g.T
gov_p_usage_t_0717_g = gov_p_usage_t_0717.groupby(['LOCATION']).agg({"gov_UTL_RATE" : np.mean})
gov_p_usage_t_0717_t = gov_p_usage_t_0717_g.T
gov_p_usage_t_0817_g = gov_p_usage_t_0817.groupby(['LOCATION']).agg({"gov_UTL_RATE" : np.mean})
gov_p_usage_t_0817_t = gov_p_usage_t_0817_g.T
gov_p_usage_t_0917_g = gov_p_usage_t_0917.groupby(['LOCATION']).agg({"gov_UTL_RATE" : np.mean})
gov_p_usage_t_0917_t = gov_p_usage_t_0917_g.T
gov_p_usage_t_1017_g = gov_p_usage_t_1017.groupby(['LOCATION']).agg({"gov_UTL_RATE" : np.mean})
gov_p_usage_t_1017_t = gov_p_usage_t_1017_g.T
gov_p_usage_t_1117_g = gov_p_usage_t_1117.groupby(['LOCATION']).agg({"gov_UTL_RATE" : np.mean})
gov_p_usage_t_1117_t = gov_p_usage_t_1117_g.T
gov_p_usage_t_1217_g = gov_p_usage_t_1217.groupby(['LOCATION']).agg({"gov_UTL_RATE" : np.mean})
gov_p_usage_t_1217_t = gov_p_usage_t_1217_g.T

gov_p_usage_t_0118_g = gov_p_usage_t_0118.groupby(['LOCATION']).agg({"gov_UTL_RATE" : np.mean})
gov_p_usage_t_0118_t = gov_p_usage_t_0118_g.T
gov_p_usage_t_0218_g = gov_p_usage_t_0218.groupby(['LOCATION']).agg({"gov_UTL_RATE" : np.mean})
gov_p_usage_t_0218_t = gov_p_usage_t_0218_g.T
gov_p_usage_t_0318_g = gov_p_usage_t_0318.groupby(['LOCATION']).agg({"gov_UTL_RATE" : np.mean})
gov_p_usage_t_0318_t = gov_p_usage_t_0318_g.T
gov_p_usage_t_0418_g = gov_p_usage_t_0418.groupby(['LOCATION']).agg({"gov_UTL_RATE" : np.mean})
gov_p_usage_t_0418_t = gov_p_usage_t_0418_g.T
gov_p_usage_t_0518_g = gov_p_usage_t_0518.groupby(['LOCATION']).agg({"gov_UTL_RATE" : np.mean})
gov_p_usage_t_0518_t = gov_p_usage_t_0518_g.T
gov_p_usage_t_0618_g = gov_p_usage_t_0618.groupby(['LOCATION']).agg({"gov_UTL_RATE" : np.mean})
gov_p_usage_t_0618_t = gov_p_usage_t_0618_g.T
gov_p_usage_t_0718_g = gov_p_usage_t_0718.groupby(['LOCATION']).agg({"gov_UTL_RATE" : np.mean})
gov_p_usage_t_0718_t = gov_p_usage_t_0718_g.T
gov_p_usage_t_0818_g = gov_p_usage_t_0818.groupby(['LOCATION']).agg({"gov_UTL_RATE" : np.mean})
gov_p_usage_t_0818_t = gov_p_usage_t_0818_g.T
gov_p_usage_t_0918_g = gov_p_usage_t_0918.groupby(['LOCATION']).agg({"gov_UTL_RATE" : np.mean})
gov_p_usage_t_0918_t = gov_p_usage_t_0918_g.T
gov_p_usage_t_1018_g = gov_p_usage_t_1018.groupby(['LOCATION']).agg({"gov_UTL_RATE" : np.mean})
gov_p_usage_t_1018_t = gov_p_usage_t_1018_g.T
gov_p_usage_t_1118_g = gov_p_usage_t_1118.groupby(['LOCATION']).agg({"gov_UTL_RATE" : np.mean})
gov_p_usage_t_1118_t = gov_p_usage_t_1118_g.T
gov_p_usage_t_1218_g = gov_p_usage_t_1218.groupby(['LOCATION']).agg({"gov_UTL_RATE" : np.mean})
gov_p_usage_t_1218_t = gov_p_usage_t_1218_g.T

gov_p_usage_t_0119_g = gov_p_usage_t_0119.groupby(['LOCATION']).agg({"gov_UTL_RATE" : np.mean})
gov_p_usage_t_0119_t = gov_p_usage_t_0119_g.T
gov_p_usage_t_0219_g = gov_p_usage_t_0219.groupby(['LOCATION']).agg({"gov_UTL_RATE" : np.mean})
gov_p_usage_t_0219_t = gov_p_usage_t_0219_g.T
gov_p_usage_t_0319_g = gov_p_usage_t_0319.groupby(['LOCATION']).agg({"gov_UTL_RATE" : np.mean})
gov_p_usage_t_0319_t = gov_p_usage_t_0319_g.T
gov_p_usage_t_0419_g = gov_p_usage_t_0419.groupby(['LOCATION']).agg({"gov_UTL_RATE" : np.mean})
gov_p_usage_t_0419_t = gov_p_usage_t_0419_g.T
gov_p_usage_t_0519_g = gov_p_usage_t_0519.groupby(['LOCATION']).agg({"gov_UTL_RATE" : np.mean})
gov_p_usage_t_0519_t = gov_p_usage_t_0519_g.T
gov_p_usage_t_0619_g = gov_p_usage_t_0619.groupby(['LOCATION']).agg({"gov_UTL_RATE" : np.mean})
gov_p_usage_t_0619_t = gov_p_usage_t_0619_g.T
gov_p_usage_t_0719_g = gov_p_usage_t_0719.groupby(['LOCATION']).agg({"gov_UTL_RATE" : np.mean})
gov_p_usage_t_0719_t = gov_p_usage_t_0719_g.T
gov_p_usage_t_0819_g = gov_p_usage_t_0819.groupby(['LOCATION']).agg({"gov_UTL_RATE" : np.mean})
gov_p_usage_t_0819_t = gov_p_usage_t_0819_g.T
gov_p_usage_t_0919_g = gov_p_usage_t_0919.groupby(['LOCATION']).agg({"gov_UTL_RATE" : np.mean})
gov_p_usage_t_0919_t = gov_p_usage_t_0919_g.T
gov_p_usage_t_1019_g = gov_p_usage_t_1019.groupby(['LOCATION']).agg({"gov_UTL_RATE" : np.mean})
gov_p_usage_t_1019_t = gov_p_usage_t_1019_g.T
gov_p_usage_t_1119_g = gov_p_usage_t_1119.groupby(['LOCATION']).agg({"gov_UTL_RATE" : np.mean})
gov_p_usage_t_1119_t = gov_p_usage_t_1119_g.T
gov_p_usage_t_1219_g = gov_p_usage_t_1219.groupby(['LOCATION']).agg({"gov_UTL_RATE" : np.mean})
gov_p_usage_t_1219_t = gov_p_usage_t_1219_g.T


gov_p_usage_t_0120_g = gov_p_usage_t_0120.groupby(['LOCATION']).agg({"gov_UTL_RATE" : np.mean})
gov_p_usage_t_0120_t = gov_p_usage_t_0120_g.T
gov_p_usage_t_0220_g = gov_p_usage_t_0220.groupby(['LOCATION']).agg({"gov_UTL_RATE" : np.mean})
gov_p_usage_t_0220_t = gov_p_usage_t_0220_g.T
gov_p_usage_t_0320_g = gov_p_usage_t_0320.groupby(['LOCATION']).agg({"gov_UTL_RATE" : np.mean})
gov_p_usage_t_0320_t = gov_p_usage_t_0320_g.T
gov_p_usage_t_0420_g = gov_p_usage_t_0420.groupby(['LOCATION']).agg({"gov_UTL_RATE" : np.mean})
gov_p_usage_t_0420_t = gov_p_usage_t_0420_g.T
gov_p_usage_t_0520_g = gov_p_usage_t_0520.groupby(['LOCATION']).agg({"gov_UTL_RATE" : np.mean})
gov_p_usage_t_0520_t = gov_p_usage_t_0520_g.T
gov_p_usage_t_0620_g = gov_p_usage_t_0620.groupby(['LOCATION']).agg({"gov_UTL_RATE" : np.mean})
gov_p_usage_t_0620_t = gov_p_usage_t_0620_g.T
gov_p_usage_t_0720_g = gov_p_usage_t_0720.groupby(['LOCATION']).agg({"gov_UTL_RATE" : np.mean})
gov_p_usage_t_0720_t = gov_p_usage_t_0720_g.T
gov_p_usage_t_0820_g = gov_p_usage_t_0820.groupby(['LOCATION']).agg({"gov_UTL_RATE" : np.mean})
gov_p_usage_t_0820_t = gov_p_usage_t_0820_g.T
gov_p_usage_t_0920_g = gov_p_usage_t_0920.groupby(['LOCATION']).agg({"gov_UTL_RATE" : np.mean})
gov_p_usage_t_0920_t = gov_p_usage_t_0920_g.T
gov_p_usage_t_1020_g = gov_p_usage_t_1020.groupby(['LOCATION']).agg({"gov_UTL_RATE" : np.mean})
gov_p_usage_t_1020_t = gov_p_usage_t_1020_g.T
gov_p_usage_t_1120_g = gov_p_usage_t_1120.groupby(['LOCATION']).agg({"gov_UTL_RATE" : np.mean})
gov_p_usage_t_1120_t = gov_p_usage_t_1120_g.T
gov_p_usage_t_1220_g = gov_p_usage_t_1220.groupby(['LOCATION']).agg({"gov_UTL_RATE" : np.mean})
gov_p_usage_t_1220_t = gov_p_usage_t_1220_g.T

In [104]:
gov_p_usage_2013 = pd.concat([gov_p_usage_t_0113_t, gov_p_usage_t_0213_t, gov_p_usage_t_0313_t, gov_p_usage_t_0413_t, gov_p_usage_t_0513_t,
                             gov_p_usage_t_0613_t, gov_p_usage_t_0713_t, gov_p_usage_t_0813_t,gov_p_usage_t_0913_t, gov_p_usage_t_1013_t,
                             gov_p_usage_t_1113_t, gov_p_usage_t_1213_t])

gov_p_usage_2014 = pd.concat([gov_p_usage_t_0114_t, gov_p_usage_t_0214_t, gov_p_usage_t_0314_t, gov_p_usage_t_0414_t, gov_p_usage_t_0514_t,
                             gov_p_usage_t_0614_t, gov_p_usage_t_0714_t, gov_p_usage_t_0814_t,gov_p_usage_t_0914_t, gov_p_usage_t_1014_t,
                             gov_p_usage_t_1114_t, gov_p_usage_t_1214_t])

gov_p_usage_2015 = pd.concat([gov_p_usage_t_0115_t, gov_p_usage_t_0215_t, gov_p_usage_t_0315_t, gov_p_usage_t_0415_t, gov_p_usage_t_0515_t,
                             gov_p_usage_t_0615_t, gov_p_usage_t_0715_t, gov_p_usage_t_0815_t,gov_p_usage_t_0915_t, gov_p_usage_t_1015_t,
                             gov_p_usage_t_1115_t, gov_p_usage_t_1215_t])

gov_p_usage_2016 = pd.concat([gov_p_usage_t_0116_t, gov_p_usage_t_0216_t, gov_p_usage_t_0316_t, gov_p_usage_t_0416_t, gov_p_usage_t_0516_t,
                             gov_p_usage_t_0616_t, gov_p_usage_t_0716_t, gov_p_usage_t_0816_t,gov_p_usage_t_0916_t, gov_p_usage_t_1016_t,
                             gov_p_usage_t_1116_t, gov_p_usage_t_1216_t])

gov_p_usage_2017 = pd.concat([gov_p_usage_t_0117_t, gov_p_usage_t_0217_t, gov_p_usage_t_0317_t, gov_p_usage_t_0417_t, gov_p_usage_t_0517_t,
                             gov_p_usage_t_0617_t, gov_p_usage_t_0717_t, gov_p_usage_t_0817_t,gov_p_usage_t_0917_t, gov_p_usage_t_1017_t,
                             gov_p_usage_t_1117_t, gov_p_usage_t_1217_t])

gov_p_usage_2018 = pd.concat([gov_p_usage_t_0118_t, gov_p_usage_t_0218_t, gov_p_usage_t_0318_t, gov_p_usage_t_0418_t, gov_p_usage_t_0518_t,
                             gov_p_usage_t_0618_t, gov_p_usage_t_0718_t, gov_p_usage_t_0818_t,gov_p_usage_t_0918_t, gov_p_usage_t_1018_t,
                             gov_p_usage_t_1118_t, gov_p_usage_t_1218_t])

gov_p_usage_2019 = pd.concat([gov_p_usage_t_0119_t, gov_p_usage_t_0219_t, gov_p_usage_t_0319_t, gov_p_usage_t_0419_t, gov_p_usage_t_0519_t,
                             gov_p_usage_t_0619_t, gov_p_usage_t_0719_t, gov_p_usage_t_0819_t,gov_p_usage_t_0919_t, gov_p_usage_t_1019_t,
                             gov_p_usage_t_1119_t, gov_p_usage_t_1219_t])


gov_p_usage_2020 = pd.concat([gov_p_usage_t_0120_t, gov_p_usage_t_0220_t, gov_p_usage_t_0320_t, gov_p_usage_t_0420_t, gov_p_usage_t_0520_t,
                             gov_p_usage_t_0620_t, gov_p_usage_t_0720_t, gov_p_usage_t_0820_t,gov_p_usage_t_0920_t, gov_p_usage_t_1020_t,
                             gov_p_usage_t_1120_t, gov_p_usage_t_1220_t])

In [105]:
gov_p_usage_sum = pd.concat([gov_p_usage_2013, gov_p_usage_2014, gov_p_usage_2015, gov_p_usage_2016,
                             gov_p_usage_2017,gov_p_usage_2018, gov_p_usage_2019, gov_p_usage_2020])
gov_p_usage_sum

,Aberdeen,City Hall,Kennedy Town,Kwai Fong,Middle Road,Murray Road,Rumsey Street,Shau Kei Wan,Sheung Fung Street,Star Ferry,Tin Hau,Tsuen Wan,Tsuen Wan Transport Complex,Yau Ma Tei
gov_UTL_RATE,64.451827,15.151515,90.256410,27.224199,31.974522,34.704370,44.525547,67.454068,67.896679,38.648649,60.798122,42.122720,20.308483,31.347150
gov_UTL_RATE,64.451827,13.333333,90.256410,27.580071,28.917197,32.390746,51.581509,70.078740,71.955720,35.405405,62.441315,45.605307,NaN,29.533679
gov_UTL_RATE,65.780731,13.939394,90.256410,28.825623,31.337580,34.704370,49.756691,71.653543,69.741697,38.378378,60.563380,47.927032,NaN,30.699482
gov_UTL_RATE,67.774086,15.151515,90.769231,30.071174,31.210191,34.961440,49.513382,73.753281,70.479705,37.567568,57.746479,47.761194,NaN,31.476684
gov_UTL_RATE,68.106312,16.969697,90.769231,32.028470,34.012739,35.989717,51.459854,75.065617,71.217712,40.000000,57.042254,45.771144,NaN,33.419689
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
gov_UTL_RATE,77.474403,27.647059,78.974359,71.563089,NaN,NaN,43.473054,79.220779,82.397004,37.400531,68.224299,81.467890,NaN,51.948052
gov_UTL_RATE,75.426621,31.764706,77.435897,71.939736,NaN,NaN,45.628743,78.441558,79.026217,41.909814,68.691589,82.201835,NaN,55.324675
gov_UTL_RATE,76.450512,31.176471,78.461538,72.504708,NaN,NaN,36.407186,78.961039,78.651685,42.970822,67.289720,83.853211,NaN,51.038961
gov_UTL_RATE,78.498294,32.941176,77.948718,71.374765,NaN,NaN,37.964072,79.480519,79.026217,44.827586,69.158879,82.385321,NaN,74.545455
gov_UTL_RATE,76.450512,26.470588,80.512821,73.069680,NaN,NaN,37.604790,80.779221,77.528090,40.053050,68.925234,83.119266,NaN,60.571429

In [106]:
gov_p_usage_sum['YR_MTH'] = ['201301', '201302', '201303', '201304', '201305', '201306', '201307', '201308','201309', '201310', '201311','201312',
                             '201401', '201402', '201403', '201404', '201405', '201406', '201407', '201408','201409', '201410', '201411','201412',
                             '201501', '201502', '201503', '201504', '201505', '201506', '201507', '201508','201509', '201510', '201511','201512',
                             '201601', '201602', '201603', '201604', '201605', '201606', '201607', '201608','201609', '201610', '201611','201612',
                             '201701', '201702', '201703', '201704', '201705', '201706', '201707', '201708','201709', '201710', '201711','201712',
                             '201801', '201802', '201803', '201804', '201805', '201806', '201807', '201808','201809', '201810', '201811','201812',
                             '201901', '201902', '201903', '201904', '201905', '201906', '201907', '201908','201909', '201910', '201911','201912'
                             , '202001', '202002', '202003', '202004', '202005', '202006', '202007', '202008',
                              '202009', '202010', '202011','202012']

In [107]:
gov_p_usage_sum.rename(columns ={'Aberdeen': 'Aberdeen_gov_UTL_RATE', 'City Hall': 'City_Hall_gov_UTL_RATE',
                                 'Kennedy Town': 'Kennedy_Town_gov_UTL_RATE', 'Kwai Fong':'Kwai_Fong_gov_UTL_RATE',
                                'Rumsey Street':'Rumsey_Street_gov_UTL_RATE', 'Shau Kei Wan':'Shau_Kei_Wan_gov_UTL_RATE',
                                'Sheung Fung Street':'Sheung_Fung_Street_gov_UTL_RATE', 'Star Ferry':'Star_Ferry_gov_UTL_RATE',
                                'Tin Hau':'Tin_Hau_gov_UTL_RATE', 'Tsuen Wan':'Tsuen_Wan_gov_UTL_RATE', 'Yau Ma Tei':'Yau_Ma_Tei_gov_UTL_RATE'}
           , inplace = True)

In [108]:
gov_p_usage_sum

,Aberdeen_gov_UTL_RATE,City_Hall_gov_UTL_RATE,Kennedy_Town_gov_UTL_RATE,Kwai_Fong_gov_UTL_RATE,Middle Road,Murray Road,Rumsey_Street_gov_UTL_RATE,Shau_Kei_Wan_gov_UTL_RATE,Sheung_Fung_Street_gov_UTL_RATE,Star_Ferry_gov_UTL_RATE,Tin_Hau_gov_UTL_RATE,Tsuen_Wan_gov_UTL_RATE,Tsuen Wan Transport Complex,Yau_Ma_Tei_gov_UTL_RATE,YR_MTH
gov_UTL_RATE,64.451827,15.151515,90.256410,27.224199,31.974522,34.704370,44.525547,67.454068,67.896679,38.648649,60.798122,42.122720,20.308483,31.347150,201301
gov_UTL_RATE,64.451827,13.333333,90.256410,27.580071,28.917197,32.390746,51.581509,70.078740,71.955720,35.405405,62.441315,45.605307,NaN,29.533679,201302
gov_UTL_RATE,65.780731,13.939394,90.256410,28.825623,31.337580,34.704370,49.756691,71.653543,69.741697,38.378378,60.563380,47.927032,NaN,30.699482,201303
gov_UTL_RATE,67.774086,15.151515,90.769231,30.071174,31.210191,34.961440,49.513382,73.753281,70.479705,37.567568,57.746479,47.761194,NaN,31.476684,201304
gov_UTL_RATE,68.106312,16.969697,90.769231,32.028470,34.012739,35.989717,51.459854,75.065617,71.217712,40.000000,57.042254,45.771144,NaN,33.419689,201305
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
gov_UTL_RATE,77.474403,27.647059,78.974359,71.563089,NaN,NaN,43.473054,79.220779,82.397004,37.400531,68.224299,81.467890,NaN,51.948052,202008
gov_UTL_RATE,75.426621,31.764706,77.435897,71.939736,NaN,NaN,45.628743,78.441558,79.026217,41.909814,68.691589,82.201835,NaN,55.324675,202009
gov_UTL_RATE,76.450512,31.176471,78.461538,72.504708,NaN,NaN,36.407186,78.961039,78.651685,42.970822,67.289720,83.853211,NaN,51.038961,202010
gov_UTL_RATE,78.498294,32.941176,77.948718,71.374765,NaN,NaN,37.964072,79.480519,79.026217,44.827586,69.158879,82.385321,NaN,74.545455,202011
gov_UTL_RATE,76.450512,26.470588,80.512821,73.069680,NaN,NaN,37.604790,80.779221,77.528090,40.053050,68.925234,83.119266,NaN,60.571429,202012

In [122]:
print("Columns in the government multi-storey parking statistics data set: ")
print('\v')
for col in gov_p_usage_sum.columns:
    print("[",col,"]")

Columns in the government multi-storey parking statistics data set:

[ Aberdeen_gov_UTL_RATE ]
[ City_Hall_gov_UTL_RATE ]
[ Kennedy_Town_gov_UTL_RATE ]
[ Kwai_Fong_gov_UTL_RATE ]
[ Middle Road ]
[ Murray Road ]
[ Rumsey_Street_gov_UTL_RATE ]
[ Shau_Kei_Wan_gov_UTL_RATE ]
[ Sheung_Fung_Street_gov_UTL_RATE ]
[ Star_Ferry_gov_UTL_RATE ]
[ Tin_Hau_gov_UTL_RATE ]
[ Tsuen_Wan_gov_UTL_RATE ]
[ Tsuen Wan Transport Complex ]
[ Yau_Ma_Tei_gov_UTL_RATE ]
[ YR_MTH ]

In [109]:
#gov_p_usage_sum.to_csv('gov_parking_processed_final.csv')