# Import packages

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.linear_model import LinearRegression
import statsmodels.api as sm
import seaborn as sns
from datetime import datetime

# Read the dataset

In [2]:
pub = pd.read_csv('https://raw.githubusercontent.com/wingochau/Dissertation/main/Car%20park%20utilisation/Public%20car%20park/public_parkingslot_table62_eng.csv')

In [3]:
pub_p = pub.loc[(pub['YR_MTH'] >= 201301)]

In [4]:
pub.head(5)

   YR_MTH REGION  NO_METER_PS   UTL_RATE
0  201301     HK         2540  40.072366
1  201301    KLN         6692  46.585893
2  201301     NT         8806  29.149911
3  201302     HK         2546  40.105163
4  201302    KLN         6687  44.442349

In [5]:
pub_p_usage = pub_p.groupby(['YR_MTH','REGION']).agg({"UTL_RATE" : np.mean})
pub_p_usage.rename(columns ={'UTL_RATE': 'pub_UTL_RATE'}, inplace=True)
pub_p_usage.head(15)

               pub_UTL_RATE
YR_MTH REGION
201301 HK         40.072366
       KLN        46.585893
       NT         29.149911
201302 HK         40.105163
       KLN        44.442349
       NT         29.543280
201303 HK         40.859455
       KLN        45.805886
       NT         29.506165
201304 HK         40.381441
       KLN        45.544363
       NT         29.061234
201305 HK         41.200214
       KLN        46.100825
       NT         28.797501

In [6]:
#pub_p_usage.to_csv('pub_parking_processed.csv')

In [7]:
pub_p_usage_t = pub_p_usage.reset_index()

In [8]:
pub_p_usage_t_0113 = pub_p_usage_t.loc[(pub_p_usage_t['YR_MTH'] == 201301)]
pub_p_usage_t_0213 = pub_p_usage_t.loc[(pub_p_usage_t['YR_MTH'] == 201302)]
pub_p_usage_t_0313 = pub_p_usage_t.loc[(pub_p_usage_t['YR_MTH'] == 201303)]
pub_p_usage_t_0413 = pub_p_usage_t.loc[(pub_p_usage_t['YR_MTH'] == 201304)]
pub_p_usage_t_0513 = pub_p_usage_t.loc[(pub_p_usage_t['YR_MTH'] == 201305)]
pub_p_usage_t_0613 = pub_p_usage_t.loc[(pub_p_usage_t['YR_MTH'] == 201306)]
pub_p_usage_t_0713 = pub_p_usage_t.loc[(pub_p_usage_t['YR_MTH'] == 201307)]
pub_p_usage_t_0813 = pub_p_usage_t.loc[(pub_p_usage_t['YR_MTH'] == 201308)]
pub_p_usage_t_0913 = pub_p_usage_t.loc[(pub_p_usage_t['YR_MTH'] == 201309)]
pub_p_usage_t_1013 = pub_p_usage_t.loc[(pub_p_usage_t['YR_MTH'] == 201310)]
pub_p_usage_t_1113 = pub_p_usage_t.loc[(pub_p_usage_t['YR_MTH'] == 201311)]
pub_p_usage_t_1213 = pub_p_usage_t.loc[(pub_p_usage_t['YR_MTH'] == 201312)]

pub_p_usage_t_0114 = pub_p_usage_t.loc[(pub_p_usage_t['YR_MTH'] == 201401)]
pub_p_usage_t_0214 = pub_p_usage_t.loc[(pub_p_usage_t['YR_MTH'] == 201402)]
pub_p_usage_t_0314 = pub_p_usage_t.loc[(pub_p_usage_t['YR_MTH'] == 201403)]
pub_p_usage_t_0414 = pub_p_usage_t.loc[(pub_p_usage_t['YR_MTH'] == 201404)]
pub_p_usage_t_0514 = pub_p_usage_t.loc[(pub_p_usage_t['YR_MTH'] == 201405)]
pub_p_usage_t_0614 = pub_p_usage_t.loc[(pub_p_usage_t['YR_MTH'] == 201406)]
pub_p_usage_t_0714 = pub_p_usage_t.loc[(pub_p_usage_t['YR_MTH'] == 201407)]
pub_p_usage_t_0814 = pub_p_usage_t.loc[(pub_p_usage_t['YR_MTH'] == 201408)]
pub_p_usage_t_0914 = pub_p_usage_t.loc[(pub_p_usage_t['YR_MTH'] == 201409)]
pub_p_usage_t_1014 = pub_p_usage_t.loc[(pub_p_usage_t['YR_MTH'] == 201410)]
pub_p_usage_t_1114 = pub_p_usage_t.loc[(pub_p_usage_t['YR_MTH'] == 201411)]
pub_p_usage_t_1214 = pub_p_usage_t.loc[(pub_p_usage_t['YR_MTH'] == 201412)]

pub_p_usage_t_0115 = pub_p_usage_t.loc[(pub_p_usage_t['YR_MTH'] == 201501)]
pub_p_usage_t_0215 = pub_p_usage_t.loc[(pub_p_usage_t['YR_MTH'] == 201502)]
pub_p_usage_t_0315 = pub_p_usage_t.loc[(pub_p_usage_t['YR_MTH'] == 201503)]
pub_p_usage_t_0415 = pub_p_usage_t.loc[(pub_p_usage_t['YR_MTH'] == 201504)]
pub_p_usage_t_0515 = pub_p_usage_t.loc[(pub_p_usage_t['YR_MTH'] == 201505)]
pub_p_usage_t_0615 = pub_p_usage_t.loc[(pub_p_usage_t['YR_MTH'] == 201506)]
pub_p_usage_t_0715 = pub_p_usage_t.loc[(pub_p_usage_t['YR_MTH'] == 201507)]
pub_p_usage_t_0815 = pub_p_usage_t.loc[(pub_p_usage_t['YR_MTH'] == 201508)]
pub_p_usage_t_0915 = pub_p_usage_t.loc[(pub_p_usage_t['YR_MTH'] == 201509)]
pub_p_usage_t_1015 = pub_p_usage_t.loc[(pub_p_usage_t['YR_MTH'] == 201510)]
pub_p_usage_t_1115 = pub_p_usage_t.loc[(pub_p_usage_t['YR_MTH'] == 201511)]
pub_p_usage_t_1215 = pub_p_usage_t.loc[(pub_p_usage_t['YR_MTH'] == 201512)]

pub_p_usage_t_0116 = pub_p_usage_t.loc[(pub_p_usage_t['YR_MTH'] == 201601)]
pub_p_usage_t_0216 = pub_p_usage_t.loc[(pub_p_usage_t['YR_MTH'] == 201602)]
pub_p_usage_t_0316 = pub_p_usage_t.loc[(pub_p_usage_t['YR_MTH'] == 201603)]
pub_p_usage_t_0416 = pub_p_usage_t.loc[(pub_p_usage_t['YR_MTH'] == 201604)]
pub_p_usage_t_0516 = pub_p_usage_t.loc[(pub_p_usage_t['YR_MTH'] == 201605)]
pub_p_usage_t_0616 = pub_p_usage_t.loc[(pub_p_usage_t['YR_MTH'] == 201606)]
pub_p_usage_t_0716 = pub_p_usage_t.loc[(pub_p_usage_t['YR_MTH'] == 201607)]
pub_p_usage_t_0816 = pub_p_usage_t.loc[(pub_p_usage_t['YR_MTH'] == 201608)]
pub_p_usage_t_0916 = pub_p_usage_t.loc[(pub_p_usage_t['YR_MTH'] == 201609)]
pub_p_usage_t_1016 = pub_p_usage_t.loc[(pub_p_usage_t['YR_MTH'] == 201610)]
pub_p_usage_t_1116 = pub_p_usage_t.loc[(pub_p_usage_t['YR_MTH'] == 201611)]
pub_p_usage_t_1216 = pub_p_usage_t.loc[(pub_p_usage_t['YR_MTH'] == 201612)]

pub_p_usage_t_0117 = pub_p_usage_t.loc[(pub_p_usage_t['YR_MTH'] == 201701)]
pub_p_usage_t_0217 = pub_p_usage_t.loc[(pub_p_usage_t['YR_MTH'] == 201702)]
pub_p_usage_t_0317 = pub_p_usage_t.loc[(pub_p_usage_t['YR_MTH'] == 201703)]
pub_p_usage_t_0417 = pub_p_usage_t.loc[(pub_p_usage_t['YR_MTH'] == 201704)]
pub_p_usage_t_0517 = pub_p_usage_t.loc[(pub_p_usage_t['YR_MTH'] == 201705)]
pub_p_usage_t_0617 = pub_p_usage_t.loc[(pub_p_usage_t['YR_MTH'] == 201706)]
pub_p_usage_t_0717 = pub_p_usage_t.loc[(pub_p_usage_t['YR_MTH'] == 201707)]
pub_p_usage_t_0817 = pub_p_usage_t.loc[(pub_p_usage_t['YR_MTH'] == 201708)]
pub_p_usage_t_0917 = pub_p_usage_t.loc[(pub_p_usage_t['YR_MTH'] == 201709)]
pub_p_usage_t_1017 = pub_p_usage_t.loc[(pub_p_usage_t['YR_MTH'] == 201710)]
pub_p_usage_t_1117 = pub_p_usage_t.loc[(pub_p_usage_t['YR_MTH'] == 201711)]
pub_p_usage_t_1217 = pub_p_usage_t.loc[(pub_p_usage_t['YR_MTH'] == 201712)]

pub_p_usage_t_0118 = pub_p_usage_t.loc[(pub_p_usage_t['YR_MTH'] == 201801)]
pub_p_usage_t_0218 = pub_p_usage_t.loc[(pub_p_usage_t['YR_MTH'] == 201802)]
pub_p_usage_t_0318 = pub_p_usage_t.loc[(pub_p_usage_t['YR_MTH'] == 201803)]
pub_p_usage_t_0418 = pub_p_usage_t.loc[(pub_p_usage_t['YR_MTH'] == 201804)]
pub_p_usage_t_0518 = pub_p_usage_t.loc[(pub_p_usage_t['YR_MTH'] == 201805)]
pub_p_usage_t_0618 = pub_p_usage_t.loc[(pub_p_usage_t['YR_MTH'] == 201806)]
pub_p_usage_t_0718 = pub_p_usage_t.loc[(pub_p_usage_t['YR_MTH'] == 201807)]
pub_p_usage_t_0818 = pub_p_usage_t.loc[(pub_p_usage_t['YR_MTH'] == 201808)]
pub_p_usage_t_0918 = pub_p_usage_t.loc[(pub_p_usage_t['YR_MTH'] == 201809)]
pub_p_usage_t_1018 = pub_p_usage_t.loc[(pub_p_usage_t['YR_MTH'] == 201810)]
pub_p_usage_t_1118 = pub_p_usage_t.loc[(pub_p_usage_t['YR_MTH'] == 201811)]
pub_p_usage_t_1218 = pub_p_usage_t.loc[(pub_p_usage_t['YR_MTH'] == 201812)]

pub_p_usage_t_0119 = pub_p_usage_t.loc[(pub_p_usage_t['YR_MTH'] == 201901)]
pub_p_usage_t_0219 = pub_p_usage_t.loc[(pub_p_usage_t['YR_MTH'] == 201902)]
pub_p_usage_t_0319 = pub_p_usage_t.loc[(pub_p_usage_t['YR_MTH'] == 201903)]
pub_p_usage_t_0419 = pub_p_usage_t.loc[(pub_p_usage_t['YR_MTH'] == 201904)]
pub_p_usage_t_0519 = pub_p_usage_t.loc[(pub_p_usage_t['YR_MTH'] == 201905)]
pub_p_usage_t_0619 = pub_p_usage_t.loc[(pub_p_usage_t['YR_MTH'] == 201906)]
pub_p_usage_t_0719 = pub_p_usage_t.loc[(pub_p_usage_t['YR_MTH'] == 201907)]
pub_p_usage_t_0819 = pub_p_usage_t.loc[(pub_p_usage_t['YR_MTH'] == 201908)]
pub_p_usage_t_0919 = pub_p_usage_t.loc[(pub_p_usage_t['YR_MTH'] == 201909)]
pub_p_usage_t_1019 = pub_p_usage_t.loc[(pub_p_usage_t['YR_MTH'] == 201910)]
pub_p_usage_t_1119 = pub_p_usage_t.loc[(pub_p_usage_t['YR_MTH'] == 201911)]
pub_p_usage_t_1219 = pub_p_usage_t.loc[(pub_p_usage_t['YR_MTH'] == 201912)]

pub_p_usage_t_0120 = pub_p_usage_t.loc[(pub_p_usage_t['YR_MTH'] == 202001)]
pub_p_usage_t_0220 = pub_p_usage_t.loc[(pub_p_usage_t['YR_MTH'] == 202002)]
pub_p_usage_t_0320 = pub_p_usage_t.loc[(pub_p_usage_t['YR_MTH'] == 202003)]
pub_p_usage_t_0420 = pub_p_usage_t.loc[(pub_p_usage_t['YR_MTH'] == 202004)]
pub_p_usage_t_0520 = pub_p_usage_t.loc[(pub_p_usage_t['YR_MTH'] == 202005)]
pub_p_usage_t_0620 = pub_p_usage_t.loc[(pub_p_usage_t['YR_MTH'] == 202006)]
pub_p_usage_t_0720 = pub_p_usage_t.loc[(pub_p_usage_t['YR_MTH'] == 202007)]
pub_p_usage_t_0820 = pub_p_usage_t.loc[(pub_p_usage_t['YR_MTH'] == 202008)]
pub_p_usage_t_0920 = pub_p_usage_t.loc[(pub_p_usage_t['YR_MTH'] == 202009)]
pub_p_usage_t_1020 = pub_p_usage_t.loc[(pub_p_usage_t['YR_MTH'] == 202010)]
pub_p_usage_t_1120 = pub_p_usage_t.loc[(pub_p_usage_t['YR_MTH'] == 202011)]
pub_p_usage_t_1220 = pub_p_usage_t.loc[(pub_p_usage_t['YR_MTH'] == 202012)]

In [9]:
pub_p_usage_t_0113_g = pub_p_usage_t_0113.groupby(['REGION']).agg({"pub_UTL_RATE" : np.mean})
pub_p_usage_t_0113_t = pub_p_usage_t_0113_g.T
pub_p_usage_t_0213_g = pub_p_usage_t_0213.groupby(['REGION']).agg({"pub_UTL_RATE" : np.mean})
pub_p_usage_t_0213_t = pub_p_usage_t_0213_g.T
pub_p_usage_t_0313_g = pub_p_usage_t_0313.groupby(['REGION']).agg({"pub_UTL_RATE" : np.mean})
pub_p_usage_t_0313_t = pub_p_usage_t_0313_g.T
pub_p_usage_t_0413_g = pub_p_usage_t_0413.groupby(['REGION']).agg({"pub_UTL_RATE" : np.mean})
pub_p_usage_t_0413_t = pub_p_usage_t_0413_g.T
pub_p_usage_t_0513_g = pub_p_usage_t_0513.groupby(['REGION']).agg({"pub_UTL_RATE" : np.mean})
pub_p_usage_t_0513_t = pub_p_usage_t_0513_g.T
pub_p_usage_t_0613_g = pub_p_usage_t_0613.groupby(['REGION']).agg({"pub_UTL_RATE" : np.mean})
pub_p_usage_t_0613_t = pub_p_usage_t_0613_g.T
pub_p_usage_t_0713_g = pub_p_usage_t_0713.groupby(['REGION']).agg({"pub_UTL_RATE" : np.mean})
pub_p_usage_t_0713_t = pub_p_usage_t_0713_g.T
pub_p_usage_t_0813_g = pub_p_usage_t_0813.groupby(['REGION']).agg({"pub_UTL_RATE" : np.mean})
pub_p_usage_t_0813_t = pub_p_usage_t_0813_g.T
pub_p_usage_t_0913_g = pub_p_usage_t_0913.groupby(['REGION']).agg({"pub_UTL_RATE" : np.mean})
pub_p_usage_t_0913_t = pub_p_usage_t_0913_g.T
pub_p_usage_t_1013_g = pub_p_usage_t_1013.groupby(['REGION']).agg({"pub_UTL_RATE" : np.mean})
pub_p_usage_t_1013_t = pub_p_usage_t_1013_g.T
pub_p_usage_t_1113_g = pub_p_usage_t_1113.groupby(['REGION']).agg({"pub_UTL_RATE" : np.mean})
pub_p_usage_t_1113_t = pub_p_usage_t_1113_g.T
pub_p_usage_t_1213_g = pub_p_usage_t_1213.groupby(['REGION']).agg({"pub_UTL_RATE" : np.mean})
pub_p_usage_t_1213_t = pub_p_usage_t_1213_g.T

pub_p_usage_t_0114_g = pub_p_usage_t_0114.groupby(['REGION']).agg({"pub_UTL_RATE" : np.mean})
pub_p_usage_t_0114_t = pub_p_usage_t_0114_g.T
pub_p_usage_t_0214_g = pub_p_usage_t_0214.groupby(['REGION']).agg({"pub_UTL_RATE" : np.mean})
pub_p_usage_t_0214_t = pub_p_usage_t_0214_g.T
pub_p_usage_t_0314_g = pub_p_usage_t_0314.groupby(['REGION']).agg({"pub_UTL_RATE" : np.mean})
pub_p_usage_t_0314_t = pub_p_usage_t_0314_g.T
pub_p_usage_t_0414_g = pub_p_usage_t_0414.groupby(['REGION']).agg({"pub_UTL_RATE" : np.mean})
pub_p_usage_t_0414_t = pub_p_usage_t_0414_g.T
pub_p_usage_t_0514_g = pub_p_usage_t_0514.groupby(['REGION']).agg({"pub_UTL_RATE" : np.mean})
pub_p_usage_t_0514_t = pub_p_usage_t_0514_g.T
pub_p_usage_t_0614_g = pub_p_usage_t_0614.groupby(['REGION']).agg({"pub_UTL_RATE" : np.mean})
pub_p_usage_t_0614_t = pub_p_usage_t_0614_g.T
pub_p_usage_t_0714_g = pub_p_usage_t_0714.groupby(['REGION']).agg({"pub_UTL_RATE" : np.mean})
pub_p_usage_t_0714_t = pub_p_usage_t_0714_g.T
pub_p_usage_t_0814_g = pub_p_usage_t_0814.groupby(['REGION']).agg({"pub_UTL_RATE" : np.mean})
pub_p_usage_t_0814_t = pub_p_usage_t_0814_g.T
pub_p_usage_t_0914_g = pub_p_usage_t_0914.groupby(['REGION']).agg({"pub_UTL_RATE" : np.mean})
pub_p_usage_t_0914_t = pub_p_usage_t_0914_g.T
pub_p_usage_t_1014_g = pub_p_usage_t_1014.groupby(['REGION']).agg({"pub_UTL_RATE" : np.mean})
pub_p_usage_t_1014_t = pub_p_usage_t_1014_g.T
pub_p_usage_t_1114_g = pub_p_usage_t_1114.groupby(['REGION']).agg({"pub_UTL_RATE" : np.mean})
pub_p_usage_t_1114_t = pub_p_usage_t_1114_g.T
pub_p_usage_t_1214_g = pub_p_usage_t_1214.groupby(['REGION']).agg({"pub_UTL_RATE" : np.mean})
pub_p_usage_t_1214_t = pub_p_usage_t_1214_g.T

pub_p_usage_t_0115_g = pub_p_usage_t_0115.groupby(['REGION']).agg({"pub_UTL_RATE" : np.mean})
pub_p_usage_t_0115_t = pub_p_usage_t_0115_g.T
pub_p_usage_t_0215_g = pub_p_usage_t_0215.groupby(['REGION']).agg({"pub_UTL_RATE" : np.mean})
pub_p_usage_t_0215_t = pub_p_usage_t_0215_g.T
pub_p_usage_t_0315_g = pub_p_usage_t_0315.groupby(['REGION']).agg({"pub_UTL_RATE" : np.mean})
pub_p_usage_t_0315_t = pub_p_usage_t_0315_g.T
pub_p_usage_t_0415_g = pub_p_usage_t_0415.groupby(['REGION']).agg({"pub_UTL_RATE" : np.mean})
pub_p_usage_t_0415_t = pub_p_usage_t_0415_g.T
pub_p_usage_t_0515_g = pub_p_usage_t_0515.groupby(['REGION']).agg({"pub_UTL_RATE" : np.mean})
pub_p_usage_t_0515_t = pub_p_usage_t_0515_g.T
pub_p_usage_t_0615_g = pub_p_usage_t_0615.groupby(['REGION']).agg({"pub_UTL_RATE" : np.mean})
pub_p_usage_t_0615_t = pub_p_usage_t_0615_g.T
pub_p_usage_t_0715_g = pub_p_usage_t_0715.groupby(['REGION']).agg({"pub_UTL_RATE" : np.mean})
pub_p_usage_t_0715_t = pub_p_usage_t_0715_g.T
pub_p_usage_t_0815_g = pub_p_usage_t_0815.groupby(['REGION']).agg({"pub_UTL_RATE" : np.mean})
pub_p_usage_t_0815_t = pub_p_usage_t_0815_g.T
pub_p_usage_t_0915_g = pub_p_usage_t_0915.groupby(['REGION']).agg({"pub_UTL_RATE" : np.mean})
pub_p_usage_t_0915_t = pub_p_usage_t_0915_g.T
pub_p_usage_t_1015_g = pub_p_usage_t_1015.groupby(['REGION']).agg({"pub_UTL_RATE" : np.mean})
pub_p_usage_t_1015_t = pub_p_usage_t_1015_g.T
pub_p_usage_t_1115_g = pub_p_usage_t_1115.groupby(['REGION']).agg({"pub_UTL_RATE" : np.mean})
pub_p_usage_t_1115_t = pub_p_usage_t_1115_g.T
pub_p_usage_t_1215_g = pub_p_usage_t_1215.groupby(['REGION']).agg({"pub_UTL_RATE" : np.mean})
pub_p_usage_t_1215_t = pub_p_usage_t_1215_g.T


pub_p_usage_t_0116_g = pub_p_usage_t_0116.groupby(['REGION']).agg({"pub_UTL_RATE" : np.mean})
pub_p_usage_t_0116_t = pub_p_usage_t_0116_g.T
pub_p_usage_t_0216_g = pub_p_usage_t_0216.groupby(['REGION']).agg({"pub_UTL_RATE" : np.mean})
pub_p_usage_t_0216_t = pub_p_usage_t_0216_g.T
pub_p_usage_t_0316_g = pub_p_usage_t_0316.groupby(['REGION']).agg({"pub_UTL_RATE" : np.mean})
pub_p_usage_t_0316_t = pub_p_usage_t_0316_g.T
pub_p_usage_t_0416_g = pub_p_usage_t_0416.groupby(['REGION']).agg({"pub_UTL_RATE" : np.mean})
pub_p_usage_t_0416_t = pub_p_usage_t_0416_g.T
pub_p_usage_t_0516_g = pub_p_usage_t_0516.groupby(['REGION']).agg({"pub_UTL_RATE" : np.mean})
pub_p_usage_t_0516_t = pub_p_usage_t_0516_g.T
pub_p_usage_t_0616_g = pub_p_usage_t_0616.groupby(['REGION']).agg({"pub_UTL_RATE" : np.mean})
pub_p_usage_t_0616_t = pub_p_usage_t_0616_g.T
pub_p_usage_t_0716_g = pub_p_usage_t_0716.groupby(['REGION']).agg({"pub_UTL_RATE" : np.mean})
pub_p_usage_t_0716_t = pub_p_usage_t_0716_g.T
pub_p_usage_t_0816_g = pub_p_usage_t_0816.groupby(['REGION']).agg({"pub_UTL_RATE" : np.mean})
pub_p_usage_t_0816_t = pub_p_usage_t_0816_g.T
pub_p_usage_t_0916_g = pub_p_usage_t_0916.groupby(['REGION']).agg({"pub_UTL_RATE" : np.mean})
pub_p_usage_t_0916_t = pub_p_usage_t_0916_g.T
pub_p_usage_t_1016_g = pub_p_usage_t_1016.groupby(['REGION']).agg({"pub_UTL_RATE" : np.mean})
pub_p_usage_t_1016_t = pub_p_usage_t_1016_g.T
pub_p_usage_t_1116_g = pub_p_usage_t_1116.groupby(['REGION']).agg({"pub_UTL_RATE" : np.mean})
pub_p_usage_t_1116_t = pub_p_usage_t_1116_g.T
pub_p_usage_t_1216_g = pub_p_usage_t_1216.groupby(['REGION']).agg({"pub_UTL_RATE" : np.mean})
pub_p_usage_t_1216_t = pub_p_usage_t_1216_g.T

pub_p_usage_t_0117_g = pub_p_usage_t_0117.groupby(['REGION']).agg({"pub_UTL_RATE" : np.mean})
pub_p_usage_t_0117_t = pub_p_usage_t_0117_g.T
pub_p_usage_t_0217_g = pub_p_usage_t_0217.groupby(['REGION']).agg({"pub_UTL_RATE" : np.mean})
pub_p_usage_t_0217_t = pub_p_usage_t_0217_g.T
pub_p_usage_t_0317_g = pub_p_usage_t_0317.groupby(['REGION']).agg({"pub_UTL_RATE" : np.mean})
pub_p_usage_t_0317_t = pub_p_usage_t_0317_g.T
pub_p_usage_t_0417_g = pub_p_usage_t_0417.groupby(['REGION']).agg({"pub_UTL_RATE" : np.mean})
pub_p_usage_t_0417_t = pub_p_usage_t_0417_g.T
pub_p_usage_t_0517_g = pub_p_usage_t_0517.groupby(['REGION']).agg({"pub_UTL_RATE" : np.mean})
pub_p_usage_t_0517_t = pub_p_usage_t_0517_g.T
pub_p_usage_t_0617_g = pub_p_usage_t_0617.groupby(['REGION']).agg({"pub_UTL_RATE" : np.mean})
pub_p_usage_t_0617_t = pub_p_usage_t_0617_g.T
pub_p_usage_t_0717_g = pub_p_usage_t_0717.groupby(['REGION']).agg({"pub_UTL_RATE" : np.mean})
pub_p_usage_t_0717_t = pub_p_usage_t_0717_g.T
pub_p_usage_t_0817_g = pub_p_usage_t_0817.groupby(['REGION']).agg({"pub_UTL_RATE" : np.mean})
pub_p_usage_t_0817_t = pub_p_usage_t_0817_g.T
pub_p_usage_t_0917_g = pub_p_usage_t_0917.groupby(['REGION']).agg({"pub_UTL_RATE" : np.mean})
pub_p_usage_t_0917_t = pub_p_usage_t_0917_g.T
pub_p_usage_t_1017_g = pub_p_usage_t_1017.groupby(['REGION']).agg({"pub_UTL_RATE" : np.mean})
pub_p_usage_t_1017_t = pub_p_usage_t_1017_g.T
pub_p_usage_t_1117_g = pub_p_usage_t_1117.groupby(['REGION']).agg({"pub_UTL_RATE" : np.mean})
pub_p_usage_t_1117_t = pub_p_usage_t_1117_g.T
pub_p_usage_t_1217_g = pub_p_usage_t_1217.groupby(['REGION']).agg({"pub_UTL_RATE" : np.mean})
pub_p_usage_t_1217_t = pub_p_usage_t_1217_g.T

pub_p_usage_t_0118_g = pub_p_usage_t_0118.groupby(['REGION']).agg({"pub_UTL_RATE" : np.mean})
pub_p_usage_t_0118_t = pub_p_usage_t_0118_g.T
pub_p_usage_t_0218_g = pub_p_usage_t_0218.groupby(['REGION']).agg({"pub_UTL_RATE" : np.mean})
pub_p_usage_t_0218_t = pub_p_usage_t_0218_g.T
pub_p_usage_t_0318_g = pub_p_usage_t_0318.groupby(['REGION']).agg({"pub_UTL_RATE" : np.mean})
pub_p_usage_t_0318_t = pub_p_usage_t_0318_g.T
pub_p_usage_t_0418_g = pub_p_usage_t_0418.groupby(['REGION']).agg({"pub_UTL_RATE" : np.mean})
pub_p_usage_t_0418_t = pub_p_usage_t_0418_g.T
pub_p_usage_t_0518_g = pub_p_usage_t_0518.groupby(['REGION']).agg({"pub_UTL_RATE" : np.mean})
pub_p_usage_t_0518_t = pub_p_usage_t_0518_g.T
pub_p_usage_t_0618_g = pub_p_usage_t_0618.groupby(['REGION']).agg({"pub_UTL_RATE" : np.mean})
pub_p_usage_t_0618_t = pub_p_usage_t_0618_g.T
pub_p_usage_t_0718_g = pub_p_usage_t_0718.groupby(['REGION']).agg({"pub_UTL_RATE" : np.mean})
pub_p_usage_t_0718_t = pub_p_usage_t_0718_g.T
pub_p_usage_t_0818_g = pub_p_usage_t_0818.groupby(['REGION']).agg({"pub_UTL_RATE" : np.mean})
pub_p_usage_t_0818_t = pub_p_usage_t_0818_g.T
pub_p_usage_t_0918_g = pub_p_usage_t_0918.groupby(['REGION']).agg({"pub_UTL_RATE" : np.mean})
pub_p_usage_t_0918_t = pub_p_usage_t_0918_g.T
pub_p_usage_t_1018_g = pub_p_usage_t_1018.groupby(['REGION']).agg({"pub_UTL_RATE" : np.mean})
pub_p_usage_t_1018_t = pub_p_usage_t_1018_g.T
pub_p_usage_t_1118_g = pub_p_usage_t_1118.groupby(['REGION']).agg({"pub_UTL_RATE" : np.mean})
pub_p_usage_t_1118_t = pub_p_usage_t_1118_g.T
pub_p_usage_t_1218_g = pub_p_usage_t_1218.groupby(['REGION']).agg({"pub_UTL_RATE" : np.mean})
pub_p_usage_t_1218_t = pub_p_usage_t_1218_g.T

pub_p_usage_t_0119_g = pub_p_usage_t_0119.groupby(['REGION']).agg({"pub_UTL_RATE" : np.mean})
pub_p_usage_t_0119_t = pub_p_usage_t_0119_g.T
pub_p_usage_t_0219_g = pub_p_usage_t_0219.groupby(['REGION']).agg({"pub_UTL_RATE" : np.mean})
pub_p_usage_t_0219_t = pub_p_usage_t_0219_g.T
pub_p_usage_t_0319_g = pub_p_usage_t_0319.groupby(['REGION']).agg({"pub_UTL_RATE" : np.mean})
pub_p_usage_t_0319_t = pub_p_usage_t_0319_g.T
pub_p_usage_t_0419_g = pub_p_usage_t_0419.groupby(['REGION']).agg({"pub_UTL_RATE" : np.mean})
pub_p_usage_t_0419_t = pub_p_usage_t_0419_g.T
pub_p_usage_t_0519_g = pub_p_usage_t_0519.groupby(['REGION']).agg({"pub_UTL_RATE" : np.mean})
pub_p_usage_t_0519_t = pub_p_usage_t_0519_g.T
pub_p_usage_t_0619_g = pub_p_usage_t_0619.groupby(['REGION']).agg({"pub_UTL_RATE" : np.mean})
pub_p_usage_t_0619_t = pub_p_usage_t_0619_g.T
pub_p_usage_t_0719_g = pub_p_usage_t_0719.groupby(['REGION']).agg({"pub_UTL_RATE" : np.mean})
pub_p_usage_t_0719_t = pub_p_usage_t_0719_g.T
pub_p_usage_t_0819_g = pub_p_usage_t_0819.groupby(['REGION']).agg({"pub_UTL_RATE" : np.mean})
pub_p_usage_t_0819_t = pub_p_usage_t_0819_g.T
pub_p_usage_t_0919_g = pub_p_usage_t_0919.groupby(['REGION']).agg({"pub_UTL_RATE" : np.mean})
pub_p_usage_t_0919_t = pub_p_usage_t_0919_g.T
pub_p_usage_t_1019_g = pub_p_usage_t_1019.groupby(['REGION']).agg({"pub_UTL_RATE" : np.mean})
pub_p_usage_t_1019_t = pub_p_usage_t_1019_g.T
pub_p_usage_t_1119_g = pub_p_usage_t_1119.groupby(['REGION']).agg({"pub_UTL_RATE" : np.mean})
pub_p_usage_t_1119_t = pub_p_usage_t_1119_g.T
pub_p_usage_t_1219_g = pub_p_usage_t_1219.groupby(['REGION']).agg({"pub_UTL_RATE" : np.mean})
pub_p_usage_t_1219_t = pub_p_usage_t_1219_g.T

pub_p_usage_t_0120_g = pub_p_usage_t_0120.groupby(['REGION']).agg({"pub_UTL_RATE" : np.mean})
pub_p_usage_t_0120_t = pub_p_usage_t_0120_g.T
pub_p_usage_t_0220_g = pub_p_usage_t_0220.groupby(['REGION']).agg({"pub_UTL_RATE" : np.mean})
pub_p_usage_t_0220_t = pub_p_usage_t_0220_g.T
pub_p_usage_t_0320_g = pub_p_usage_t_0320.groupby(['REGION']).agg({"pub_UTL_RATE" : np.mean})
pub_p_usage_t_0320_t = pub_p_usage_t_0320_g.T
pub_p_usage_t_0420_g = pub_p_usage_t_0420.groupby(['REGION']).agg({"pub_UTL_RATE" : np.mean})
pub_p_usage_t_0420_t = pub_p_usage_t_0420_g.T
pub_p_usage_t_0520_g = pub_p_usage_t_0520.groupby(['REGION']).agg({"pub_UTL_RATE" : np.mean})
pub_p_usage_t_0520_t = pub_p_usage_t_0520_g.T
pub_p_usage_t_0620_g = pub_p_usage_t_0620.groupby(['REGION']).agg({"pub_UTL_RATE" : np.mean})
pub_p_usage_t_0620_t = pub_p_usage_t_0620_g.T
pub_p_usage_t_0720_g = pub_p_usage_t_0720.groupby(['REGION']).agg({"pub_UTL_RATE" : np.mean})
pub_p_usage_t_0720_t = pub_p_usage_t_0720_g.T
pub_p_usage_t_0820_g = pub_p_usage_t_0820.groupby(['REGION']).agg({"pub_UTL_RATE" : np.mean})
pub_p_usage_t_0820_t = pub_p_usage_t_0820_g.T
pub_p_usage_t_0920_g = pub_p_usage_t_0920.groupby(['REGION']).agg({"pub_UTL_RATE" : np.mean})
pub_p_usage_t_0920_t = pub_p_usage_t_0920_g.T
pub_p_usage_t_1020_g = pub_p_usage_t_1020.groupby(['REGION']).agg({"pub_UTL_RATE" : np.mean})
pub_p_usage_t_1020_t = pub_p_usage_t_1020_g.T
pub_p_usage_t_1120_g = pub_p_usage_t_1120.groupby(['REGION']).agg({"pub_UTL_RATE" : np.mean})
pub_p_usage_t_1120_t = pub_p_usage_t_1120_g.T
pub_p_usage_t_1220_g = pub_p_usage_t_1220.groupby(['REGION']).agg({"pub_UTL_RATE" : np.mean})
pub_p_usage_t_1220_t = pub_p_usage_t_1220_g.T

In [10]:
pub_p_usage_2013 = pd.concat([pub_p_usage_t_0113_t, pub_p_usage_t_0213_t, pub_p_usage_t_0313_t, pub_p_usage_t_0413_t, pub_p_usage_t_0513_t,
                             pub_p_usage_t_0613_t, pub_p_usage_t_0713_t, pub_p_usage_t_0813_t,pub_p_usage_t_0913_t, pub_p_usage_t_1013_t,
                             pub_p_usage_t_1113_t, pub_p_usage_t_1213_t])

pub_p_usage_2014 = pd.concat([pub_p_usage_t_0114_t, pub_p_usage_t_0214_t, pub_p_usage_t_0314_t, pub_p_usage_t_0414_t, pub_p_usage_t_0514_t,
                             pub_p_usage_t_0614_t, pub_p_usage_t_0714_t, pub_p_usage_t_0814_t,pub_p_usage_t_0914_t, pub_p_usage_t_1014_t,
                             pub_p_usage_t_1114_t, pub_p_usage_t_1214_t])

pub_p_usage_2015 = pd.concat([pub_p_usage_t_0115_t, pub_p_usage_t_0215_t, pub_p_usage_t_0315_t, pub_p_usage_t_0415_t, pub_p_usage_t_0515_t,
                             pub_p_usage_t_0615_t, pub_p_usage_t_0715_t, pub_p_usage_t_0815_t,pub_p_usage_t_0915_t, pub_p_usage_t_1015_t,
                             pub_p_usage_t_1115_t, pub_p_usage_t_1215_t])

pub_p_usage_2016 = pd.concat([pub_p_usage_t_0116_t, pub_p_usage_t_0216_t, pub_p_usage_t_0316_t, pub_p_usage_t_0416_t, pub_p_usage_t_0516_t,
                             pub_p_usage_t_0616_t, pub_p_usage_t_0716_t, pub_p_usage_t_0816_t,pub_p_usage_t_0916_t, pub_p_usage_t_1016_t,
                             pub_p_usage_t_1116_t, pub_p_usage_t_1216_t])

pub_p_usage_2017 = pd.concat([pub_p_usage_t_0117_t, pub_p_usage_t_0217_t, pub_p_usage_t_0317_t, pub_p_usage_t_0417_t, pub_p_usage_t_0517_t,
                             pub_p_usage_t_0617_t, pub_p_usage_t_0717_t, pub_p_usage_t_0817_t,pub_p_usage_t_0917_t, pub_p_usage_t_1017_t,
                             pub_p_usage_t_1117_t, pub_p_usage_t_1217_t])

pub_p_usage_2018 = pd.concat([pub_p_usage_t_0118_t, pub_p_usage_t_0218_t, pub_p_usage_t_0318_t, pub_p_usage_t_0418_t, pub_p_usage_t_0518_t,
                             pub_p_usage_t_0618_t, pub_p_usage_t_0718_t, pub_p_usage_t_0818_t,pub_p_usage_t_0918_t, pub_p_usage_t_1018_t,
                             pub_p_usage_t_1118_t, pub_p_usage_t_1218_t])

pub_p_usage_2019 = pd.concat([pub_p_usage_t_0119_t, pub_p_usage_t_0219_t, pub_p_usage_t_0319_t, pub_p_usage_t_0419_t, pub_p_usage_t_0519_t,
                             pub_p_usage_t_0619_t, pub_p_usage_t_0719_t, pub_p_usage_t_0819_t,pub_p_usage_t_0919_t, pub_p_usage_t_1019_t,
                             pub_p_usage_t_1119_t, pub_p_usage_t_1219_t])

pub_p_usage_2020 = pd.concat([pub_p_usage_t_0120_t, pub_p_usage_t_0220_t, pub_p_usage_t_0320_t, pub_p_usage_t_0420_t, pub_p_usage_t_0520_t,
                             pub_p_usage_t_0620_t, pub_p_usage_t_0720_t, pub_p_usage_t_0820_t,pub_p_usage_t_0920_t, pub_p_usage_t_1020_t,
                             pub_p_usage_t_1120_t, pub_p_usage_t_1220_t])

In [11]:
pub_p_usage_sum = pd.concat([pub_p_usage_2013, pub_p_usage_2014, pub_p_usage_2015, pub_p_usage_2016,
                             pub_p_usage_2017, pub_p_usage_2018, pub_p_usage_2019, pub_p_usage_2020])
pub_p_usage_sum

REGION               HK        KLN         NT
pub_UTL_RATE  40.072366  46.585893  29.149911
pub_UTL_RATE  40.105163  44.442349  29.543280
pub_UTL_RATE  40.859455  45.805886  29.506165
pub_UTL_RATE  40.381441  45.544363  29.061234
pub_UTL_RATE  41.200214  46.100825  28.797501
...                 ...        ...        ...
pub_UTL_RATE  32.678356  29.760214  30.151253
pub_UTL_RATE  34.012029  30.632514  31.078170
pub_UTL_RATE  36.055434  31.435855  33.155418
pub_UTL_RATE  39.651392  34.564798  35.492288
pub_UTL_RATE  40.224327  34.565979  35.601603

[96 rows x 3 columns]

In [12]:
pub_p_usage_sum['YR_MTH'] = ['201301', '201302', '201303', '201304', '201305', '201306', '201307', '201308','201309', '201310', '201311','201312',
                             '201401', '201402', '201403', '201404', '201405', '201406', '201407', '201408','201409', '201410', '201411','201412',
                             '201501', '201502', '201503', '201504', '201505', '201506', '201507', '201508','201509', '201510', '201511','201512',
                             '201601', '201602', '201603', '201604', '201605', '201606', '201607', '201608','201609', '201610', '201611','201612',
                             '201701', '201702', '201703', '201704', '201705', '201706', '201707', '201708','201709', '201710', '201711','201712',
                             '201801', '201802', '201803', '201804', '201805', '201806', '201807', '201808','201809', '201810', '201811','201812',
                             '201901', '201902', '201903', '201904', '201905', '201906', '201907', '201908','201909', '201910', '201911','201912'
                             , '202001', '202002', '202003', '202004', '202005', '202006', '202007', '202008',
                              '202009', '202010', '202011','202012']

In [13]:
pub_p_usage_sum.rename(columns ={'HK': 'HK_pub_UTL_RATE', 'KLN': 'KLN_pub_UTL_RATE',
                                 'NT': 'NT_pub_UTL_RATE'}
           , inplace = True)

In [14]:
len(pub_p_usage_sum)

96

In [15]:
pub_p_usage_sum

REGION        HK_pub_UTL_RATE  KLN_pub_UTL_RATE  NT_pub_UTL_RATE  YR_MTH
pub_UTL_RATE        40.072366         46.585893        29.149911  201301
pub_UTL_RATE        40.105163         44.442349        29.543280  201302
pub_UTL_RATE        40.859455         45.805886        29.506165  201303
pub_UTL_RATE        40.381441         45.544363        29.061234  201304
pub_UTL_RATE        41.200214         46.100825        28.797501  201305
...                       ...               ...              ...     ...
pub_UTL_RATE        32.678356         29.760214        30.151253  202008
pub_UTL_RATE        34.012029         30.632514        31.078170  202009
pub_UTL_RATE        36.055434         31.435855        33.155418  202010
pub_UTL_RATE        39.651392         34.564798        35.492288  202011
pub_UTL_RATE        40.224327         34.565979        35.601603  202012

[96 rows x 4 columns]

In [16]:
print("Columns in the public metered parking space statistics data set: ")
print('\v')
for col in pub_p_usage_sum.columns:
    print("[",col,"]")

Columns in the public metered parking space statistics data set:

[ HK_pub_UTL_RATE ]
[ KLN_pub_UTL_RATE ]
[ NT_pub_UTL_RATE ]
[ YR_MTH ]

In [17]:
#pub_p_usage_sum.to_csv('pub_parking_processed_final.csv')